###
GET http://127.0.0.1:3000/usuarios HTTP/1.1
###
GET http://127.0.0.1:3000/usuarios/nombre/JUAN HTTP/1.1
###
GET http://127.0.0.1:3000/usuarios/apellido/martinez HTTP/1.1
###
GET http://127.0.0.1:3000/usuarios/dni/40954703 HTTP/1.1
###
###
GET http://127.0.0.1:3000/usuarios/email/facundoemanuel73@gmail.com HTTP/1.1
###
GET http://127.0.0.1:3000/usuarios/telefono/1173639902 HTTP/1.1

###
POST http://127.0.0.1:3000/usuarios/crear/ HTTP/1.1
Content-Type: application/json

{
    "nombre":"Facundo",
    "apellido": "Martinez",
    "DNI": "409547031123341",
    "email": "tuvieja4@gmail.com",
    "telefono":"1173639902"
}

###
POST http://127.0.0.1:3000/usuarios/modificar/40954703 HTTP/1.1
Content-Type: application/json

{
    "apellido":"Bueno, vamos"
}

###
DELETE http://127.0.0.1:3000/usuarios/borrar/4144151 HTTP/1.1


// Pantalla de prestamos

### PRESTAMOS - Traer todos (debería devolver [])
GET http://DESKTOP-TRDB359:3000/prestamos HTTP/1.1

### PRESTAMOS - Estadisticas
GET http://DESKTOP-TRDB359:3000/prestamos/estadisticas HTTP/1.1

### PRESTAMOS - Crear préstamo
POST http://DESKTOP-TRDB359:3000/prestamos HTTP/1.1
Content-Type: application/json

{
    "usuarioId": "6a2c82d6736ed5f23354bc96",
    "libroId": "6a221557e105f786110ae39a"
}

### PRESTAMOS - Traer por ID (reemplazás el id por el que devolvió el POST)
GET http://DESKTOP-TRDB359:3000/prestamos/6a2ed36878dd467447751989 HTTP/1.1

### PRESTAMOS - Devolver libro
PATCH http://127.0.0.1:3000/prestamos/ID_DEL_PRESTAMO HTTP/1.1

### PRESTAMOS - Eliminar préstamo
DELETE http://DESKTOP-TRDB359:3000/prestamos/6a2ed36878dd467447751989 HTTP/1.1